#!/usr/bin/env python3
import os.path
import sys
# If the development module source paths exist,
# add them to the python path
whereami = os.path.split( os.path.realpath(__file__) )
#print(f'{whereami}')
if os.path.exists(whereami[0] + '/mqpdevpath.py'):
#    print(f'Importing devpath')
    from mqpdevpath import *
    
#print(f'sys.path = {sys.path}')

from emailrobot.emailrobot import emailRobot
bot = emailRobot(True)
