#!/usr/bin/env python3
#import sys
from mydevpath import addDevtoPath

#Add development python paths to add from file

mdp=addDevtoPath('mqpdevpath.txt')

#print(f'python path:\n{sys.path}')

#import os

from emailrobot.emailrobot import emailRobot
bot = emailRobot(True)
